export const actions_types = {
  SET_TODO: "SET_TODO",
  SET_TODO_ITEM: "SET_TODO_ITEM",
  NEW_TODO_ITEM: "NEW_TODO_ITEM",
  DELETE_TODO: "DELETE_TODO",
  CHANGE_TODO_ITEM: "CHANGE_TODO_ITEM",
  ADD: "ADD",
};
